//! High-level host library for running Python code in hyperlight-wasm sandboxes.
//!
//! Uses the component model with typed bindings generated by
//! `hyperlight_component_macro::host_bindgen!`.

#![allow(renamed_and_removed_lints)]
#![allow(unknown_lints)]
#![allow(unused_unit)]

extern crate alloc;

use std::collections::{HashMap, HashSet};
use std::path::Path;
use std::sync::{Arc, Mutex};

use anyhow::{Context, Result};
use hyperlight_wasm::{LoadedWasmSandbox, SandboxBuilder};
pub use hyperlight_wasm::Snapshot;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Component model bindings (generated from the WIT)
// ---------------------------------------------------------------------------

mod bindings {
    hyperlight_component_macro::host_bindgen!("../python_sandbox/wit/python-sandbox-world.wasm");
}

mod wasi_impl;
mod virtual_fs;

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Configuration for building a [`PythonSandbox`].
pub struct SandboxConfig {
    /// Path to the AOT-compiled Wasm component (e.g. `python-sandbox.aot`).
    pub module_path: String,
    /// Guest heap size in bytes.
    pub heap_size: u64,
    /// Guest scratch / stack size in bytes.
    pub stack_size: u64,
    /// Optional wall-clock timeout (seconds) for guest execution.
    pub timeout_secs: Option<u64>,
}

// ---------------------------------------------------------------------------
// Execution result
// ---------------------------------------------------------------------------

/// The result of executing code inside the sandbox.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionResult {
    pub stdout: String,
    pub stderr: String,
    pub exit_code: i32,
    pub outputs: HashMap<String, Vec<u8>>,
}

// ---------------------------------------------------------------------------
// Tool registry (Phase 1 stub — functional but not yet wired to host fns)
// ---------------------------------------------------------------------------

/// Registry of host-side tool handlers.
pub struct ToolRegistry {
    tools: HashMap<
        String,
        Box<dyn Fn(serde_json::Value) -> Result<serde_json::Value> + Send + Sync>,
    >,
    middleware: Vec<Box<dyn Fn(&str, &serde_json::Value) -> Result<()> + Send + Sync>>,
}

impl ToolRegistry {
    pub fn new() -> Self {
        Self {
            tools: HashMap::new(),
            middleware: Vec::new(),
        }
    }

    pub fn register<F>(&mut self, name: &str, handler: F)
    where
        F: Fn(serde_json::Value) -> Result<serde_json::Value> + Send + Sync + 'static,
    {
        self.tools.insert(name.to_string(), Box::new(handler));
    }

    pub fn add_middleware<F>(&mut self, hook: F)
    where
        F: Fn(&str, &serde_json::Value) -> Result<()> + Send + Sync + 'static,
    {
        self.middleware.push(Box::new(hook));
    }

    pub fn dispatch(&self, name: &str, args: serde_json::Value) -> Result<serde_json::Value> {
        for hook in &self.middleware {
            hook(name, &args)?;
        }
        let handler = self
            .tools
            .get(name)
            .ok_or_else(|| anyhow::anyhow!("unknown tool: {}", name))?;
        handler(args)
    }
}

impl Default for ToolRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Network permissions
// ---------------------------------------------------------------------------

/// A single network permission entry — describes what the sandbox is allowed to reach.
#[derive(Debug, Clone)]
pub struct NetworkPermission {
    /// The allowed domain (e.g. "httpbin.org").
    pub domain: String,
    /// Optional path prefix (e.g. "/api/v1"). If `None`, all paths are allowed.
    pub path_prefix: Option<String>,
    /// Optional set of allowed HTTP methods. If `None`, all methods are allowed.
    pub methods: Option<HashSet<String>>,
}

/// Manages the set of allowed network destinations for a sandbox.
#[derive(Debug, Clone, Default)]
pub struct NetworkPermissions {
    permissions: Vec<NetworkPermission>,
}

impl NetworkPermissions {
    pub fn new() -> Self {
        Self { permissions: Vec::new() }
    }

    /// Add a permission. `target` can be:
    /// - A plain domain: `"httpbin.org"`
    /// - A URL with path prefix: `"https://httpbin.org/get"`
    ///
    /// `methods` optionally restricts which HTTP methods are allowed.
    pub fn allow(&mut self, target: &str, methods: Option<Vec<String>>) {
        let methods_set = methods.map(|m| m.into_iter().map(|s| s.to_uppercase()).collect());

        // Parse target: strip scheme, split host/path
        let without_scheme = target
            .strip_prefix("https://")
            .or_else(|| target.strip_prefix("http://"))
            .unwrap_or(target);

        let (domain, path_prefix) = if let Some(slash_pos) = without_scheme.find('/') {
            let d = &without_scheme[..slash_pos];
            let p = &without_scheme[slash_pos..];
            (d.to_string(), Some(p.to_string()))
        } else {
            (without_scheme.to_string(), None)
        };

        self.permissions.push(NetworkPermission {
            domain,
            path_prefix,
            methods: methods_set,
        });
    }

    /// Check if a request to the given domain + path + method is allowed.
    pub fn is_allowed(&self, domain: &str, path: &str, method: &str) -> bool {
        self.permissions.iter().any(|p| {
            if p.domain != domain {
                return false;
            }
            if let Some(ref prefix) = p.path_prefix {
                if !path.starts_with(prefix.as_str()) {
                    return false;
                }
            }
            if let Some(ref methods) = p.methods {
                if !methods.contains(&method.to_uppercase()) {
                    return false;
                }
            }
            true
        })
    }

    /// Check if a domain has any permission at all (for backward compat).
    pub fn is_domain_allowed(&self, domain: &str) -> bool {
        self.permissions.iter().any(|p| p.domain == domain)
    }
}

// ---------------------------------------------------------------------------
// WIT host interface — manual registration for tool dispatch
// ---------------------------------------------------------------------------

// The host_bindgen! macro generates export bindings (Executor trait) but its
// import registration uses Vec<u8> params which hyperlight-wasm's
// register_host_function doesn't support. So we register `dispatch` manually
// with String params and use the macro only for export calls.

/// Host state — implements tools.dispatch routing to ToolRegistry.
pub struct HostState {
    tools: ToolRegistry,
    fs: Arc<Mutex<virtual_fs::VirtualFs>>,
    network: Arc<Mutex<NetworkPermissions>>,
}

#[allow(refining_impl_trait)]
impl bindings::root::component::RootImports for HostState {
    type Tools = HostState;
    fn tools(&mut self) -> &mut Self { self }

    type Environment = HostState;
    fn environment(&mut self) -> &mut Self { self }

    type Exit = HostState;
    fn exit(&mut self) -> &mut Self { self }

    type Error = HostState;
    fn error(&mut self) -> &mut Self { self }

    type Poll = HostState;
    fn poll(&mut self) -> &mut Self { self }

    type Streams = HostState;
    fn streams(&mut self) -> &mut Self { self }

    type Stdin = HostState;
    fn stdin(&mut self) -> &mut Self { self }

    type Stdout = HostState;
    fn stdout(&mut self) -> &mut Self { self }

    type Stderr = HostState;
    fn stderr(&mut self) -> &mut Self { self }

    type TerminalInput = HostState;
    fn terminal_input(&mut self) -> &mut Self { self }

    type TerminalOutput = HostState;
    fn terminal_output(&mut self) -> &mut Self { self }

    type TerminalStdin = HostState;
    fn terminal_stdin(&mut self) -> &mut Self { self }

    type TerminalStdout = HostState;
    fn terminal_stdout(&mut self) -> &mut Self { self }

    type TerminalStderr = HostState;
    fn terminal_stderr(&mut self) -> &mut Self { self }

    type MonotonicClock = HostState;
    fn monotonic_clock(&mut self) -> &mut Self { self }

    type WallClock = HostState;
    fn wall_clock(&mut self) -> &mut Self { self }

    type FilesystemTypes = HostState;
    fn filesystem_types(&mut self) -> &mut Self { self }

    type HttpTypes = HostState;
    fn http_types(&mut self) -> &mut Self { self }

    type OutgoingHandler = HostState;
    fn outgoing_handler(&mut self) -> &mut Self { self }

    type Preopens = HostState;
    fn preopens(&mut self) -> &mut Self { self }

    type Network = HostState;
    fn network(&mut self) -> &mut Self { self }

    type InstanceNetwork = HostState;
    fn instance_network(&mut self) -> &mut Self { self }

    type Udp = HostState;
    fn udp(&mut self) -> &mut Self { self }

    type UdpCreateSocket = HostState;
    fn udp_create_socket(&mut self) -> &mut Self { self }

    type Tcp = HostState;
    fn tcp(&mut self) -> &mut Self { self }

    type TcpCreateSocket = HostState;
    fn tcp_create_socket(&mut self) -> &mut Self { self }

    type IpNameLookup = HostState;
    fn ip_name_lookup(&mut self) -> &mut Self { self }

    type Random = HostState;
    fn random(&mut self) -> &mut Self { self }

    type Insecure = HostState;
    fn insecure(&mut self) -> &mut Self { self }

    type InsecureSeed = HostState;
    fn insecure_seed(&mut self) -> &mut Self { self }
}

impl bindings::hyperlight::sandbox::Tools for HostState {
    fn dispatch(&mut self, request_json: String) -> String {
        let request: serde_json::Value = serde_json::from_str(&request_json)
            .unwrap_or(serde_json::Value::Null);
        let name = request["name"].as_str().unwrap_or("");
        let args = request.get("args").cloned().unwrap_or(serde_json::Value::Null);
        match self.tools.dispatch(name, args) {
            Ok(v) => serde_json::to_string(&serde_json::json!({"result": v}))
                .unwrap_or_else(|_| r#"{"error":"serialization failed"}"#.to_string()),
            Err(e) => serde_json::to_string(&serde_json::json!({"error": e.to_string()}))
                .unwrap_or_else(|_| r#"{"error":"serialization failed"}"#.to_string()),
        }
    }
}

// ---------------------------------------------------------------------------
// PythonSandbox
// ---------------------------------------------------------------------------

/// A ready-to-use Python execution sandbox backed by hyperlight-wasm.
pub struct PythonSandbox {
    sandbox: bindings::RootSandbox<HostState, LoadedWasmSandbox>,
    fs: Arc<Mutex<virtual_fs::VirtualFs>>,
    network: Arc<Mutex<NetworkPermissions>>,
}

impl PythonSandbox {
    /// Build a new sandbox from the given configuration.
    pub fn new(config: SandboxConfig) -> Result<Self> {
        Self::with_tools(config, ToolRegistry::new())
    }

    /// Build a new sandbox with pre-registered tools.
    pub fn with_tools(config: SandboxConfig, tools: ToolRegistry) -> Result<Self> {
        let module_path = config.module_path.clone();
        let fs = Arc::new(Mutex::new(virtual_fs::VirtualFs::new()));
        let network = Arc::new(Mutex::new(NetworkPermissions::new()));
        let state = HostState { tools, fs: fs.clone(), network: network.clone() };

        let mut proto = SandboxBuilder::new()
            .with_guest_input_buffer_size(70_000_000)
            .with_guest_heap_size(config.heap_size)
            .with_guest_scratch_size(config.stack_size as usize)
            .build()
            .context("failed to build ProtoWasmSandbox")?;

        // register_host_functions binds tools.dispatch via the macro-generated code
        let rt = bindings::register_host_functions(&mut proto, state);

        let wasm_sandbox = proto
            .load_runtime()
            .context("failed to load Wasm runtime")?;

        let sb = wasm_sandbox
            .load_module(Path::new(&module_path))
            .context("failed to load Wasm module")?;

        Ok(Self {
            sandbox: bindings::RootSandbox { sb, rt },
            fs,
            network,
        })
    }

    /// Execute Python `code` in the sandbox.
    pub fn run(&mut self, code: &str) -> Result<ExecutionResult> {
        use bindings::hyperlight::sandbox::Executor;

        // The macro-generated run() panics on guest errors (e.g. GPF from
        // stubbed WASI calls). Catch the panic and return it as an error
        // result so callers get a clean ExecutionResult instead of a crash.
        // https://github.com/hyperlight-dev/hyperlight/issues/1316
        let code_owned = code.to_string();
        let sandbox_ptr = &mut self.sandbox as *mut _ as usize;

        // Suppress the default panic hook output while we catch_unwind
        let prev_hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));

        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let sandbox = unsafe {
                &mut *(sandbox_ptr
                    as *mut bindings::RootSandbox<HostState, LoadedWasmSandbox>)
            };
            sandbox.run(code_owned)
        }));

        // Restore the original panic hook
        std::panic::set_hook(prev_hook);

        match result {
            Ok(wit_result) => {
                let outputs = self.fs.lock().unwrap().get_output_files();
                Ok(ExecutionResult {
                    stdout: wit_result.stdout,
                    stderr: wit_result.stderr,
                    exit_code: wit_result.exit_code,
                    outputs,
                })
            }
            Err(panic_info) => {
                let msg = if let Some(s) = panic_info.downcast_ref::<String>() {
                    s.clone()
                } else if let Some(s) = panic_info.downcast_ref::<&str>() {
                    s.to_string()
                } else {
                    "sandbox execution failed".to_string()
                };
                Ok(ExecutionResult {
                    stdout: String::new(),
                    stderr: msg,
                    exit_code: -1,
                    outputs: HashMap::new(),
                })
            }
        }
    }

    /// Take a snapshot of the current sandbox state.
    pub fn snapshot(&mut self) -> Result<Arc<Snapshot>> {
        self.sandbox
            .sb
            .snapshot()
            .map_err(|e| anyhow::anyhow!("snapshot failed: {e}"))
    }

    /// Restore the sandbox to a previously captured snapshot.
    pub fn restore(&mut self, snapshot: &Arc<Snapshot>) -> Result<()> {
        self.sandbox
            .sb
            .restore(snapshot.clone())
            .map_err(|e| anyhow::anyhow!("restore failed: {e}"))
    }

    // ----- Filesystem management -----

    /// Add a file to the sandbox's `/input/` directory.
    pub fn add_file(&mut self, name: &str, data: Vec<u8>) {
        self.fs.lock().unwrap().add_input_file(name, data);
    }

    /// Add files from host paths to the sandbox's `/input/` directory.
    pub fn add_files(&mut self, paths: &[&Path]) -> Result<()> {
        let mut fs = self.fs.lock().unwrap();
        for path in paths {
            let data = std::fs::read(path)
                .with_context(|| format!("failed to read file: {}", path.display()))?;
            let name = path
                .file_name()
                .ok_or_else(|| anyhow::anyhow!("path has no filename: {}", path.display()))?
                .to_str()
                .ok_or_else(|| anyhow::anyhow!("non-UTF-8 filename: {}", path.display()))?;
            fs.add_input_file(name, data);
        }
        Ok(())
    }

    /// Get all files written to `/output/` by the guest.
    pub fn get_output_files(&self) -> HashMap<String, Vec<u8>> {
        self.fs.lock().unwrap().get_output_files()
    }

    /// Clear all input/output files and streams.
    pub fn clear_files(&mut self) {
        self.fs.lock().unwrap().clear();
    }

    // ----- Network management -----

    /// Allow outbound HTTP requests to the given target.
    ///
    /// `target` can be a plain domain (`"httpbin.org"`) or a URL with path prefix
    /// (`"https://api.example.com/v1"`).
    ///
    /// `methods` optionally restricts which HTTP methods are allowed (e.g. `["GET", "POST"]`).
    /// If `None`, all methods are allowed.
    ///
    /// No network access is allowed by default — every destination must be explicitly allowed.
    pub fn allow(&mut self, target: &str, methods: Option<Vec<String>>) {
        self.network.lock().unwrap().allow(target, methods);
    }

    /// Allow outbound HTTP requests to the given domain (convenience for `allow(domain, None)`).
    pub fn add_network(&mut self, domain: &str) {
        self.network.lock().unwrap().allow(domain, None);
    }

    /// Check whether a request to the given domain/path/method is allowed.
    pub fn is_allowed(&self, domain: &str, path: &str, method: &str) -> bool {
        self.network.lock().unwrap().is_allowed(domain, path, method)
    }

    /// Check whether a domain is in the allowlist.
    pub fn is_domain_allowed(&self, domain: &str) -> bool {
        self.network.lock().unwrap().is_domain_allowed(domain)
    }
}
