//! High-level host library for running Python code in hyperlight-wasm sandboxes.
//!
//! Uses the component model with typed bindings generated by
//! `hyperlight_component_macro::host_bindgen!`.

#![allow(renamed_and_removed_lints)]
#![allow(unknown_lints)]
#![allow(unused_unit)]

extern crate alloc;

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;

use anyhow::{Context, Result};
use hyperlight_wasm::{LoadedWasmSandbox, SandboxBuilder, Snapshot};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Component model bindings (generated from the WIT)
// ---------------------------------------------------------------------------

mod bindings {
    hyperlight_component_macro::host_bindgen!("../python_sandbox/wit/python-sandbox-world.wasm");
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Configuration for building a [`PythonSandbox`].
pub struct SandboxConfig {
    /// Path to the AOT-compiled Wasm component (e.g. `python-sandbox.aot`).
    pub module_path: String,
    /// Guest heap size in bytes.
    pub heap_size: u64,
    /// Guest scratch / stack size in bytes.
    pub stack_size: u64,
    /// Optional wall-clock timeout (seconds) for guest execution.
    pub timeout_secs: Option<u64>,
}

// ---------------------------------------------------------------------------
// Execution result
// ---------------------------------------------------------------------------

/// The result of executing code inside the sandbox.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionResult {
    pub stdout: String,
    pub stderr: String,
    pub exit_code: i32,
}

// ---------------------------------------------------------------------------
// Tool registry (Phase 1 stub — functional but not yet wired to host fns)
// ---------------------------------------------------------------------------

/// Registry of host-side tool handlers.
pub struct ToolRegistry {
    tools: HashMap<
        String,
        Box<dyn Fn(serde_json::Value) -> Result<serde_json::Value> + Send + Sync>,
    >,
    middleware: Vec<Box<dyn Fn(&str, &serde_json::Value) -> Result<()> + Send + Sync>>,
}

impl ToolRegistry {
    pub fn new() -> Self {
        Self {
            tools: HashMap::new(),
            middleware: Vec::new(),
        }
    }

    pub fn register<F>(&mut self, name: &str, handler: F)
    where
        F: Fn(serde_json::Value) -> Result<serde_json::Value> + Send + Sync + 'static,
    {
        self.tools.insert(name.to_string(), Box::new(handler));
    }

    pub fn add_middleware<F>(&mut self, hook: F)
    where
        F: Fn(&str, &serde_json::Value) -> Result<()> + Send + Sync + 'static,
    {
        self.middleware.push(Box::new(hook));
    }

    pub fn dispatch(&self, name: &str, args: serde_json::Value) -> Result<serde_json::Value> {
        for hook in &self.middleware {
            hook(name, &args)?;
        }
        let handler = self
            .tools
            .get(name)
            .ok_or_else(|| anyhow::anyhow!("unknown tool: {}", name))?;
        handler(args)
    }
}

impl Default for ToolRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// WIT host interface — manual registration for tool dispatch
// ---------------------------------------------------------------------------

// The host_bindgen! macro generates export bindings (Executor trait) but its
// import registration uses Vec<u8> params which hyperlight-wasm's
// register_host_function doesn't support. So we register `dispatch` manually
// with String params and use the macro only for export calls.

/// Host state — implements tools.dispatch routing to ToolRegistry.
pub struct HostState {
    tools: ToolRegistry,
}

#[allow(refining_impl_trait)]
impl bindings::hyperlight::sandbox::PythonSandboxImports for HostState {
    type Tools = HostState;
    fn tools(&mut self) -> &mut Self { self }
}

impl bindings::hyperlight::sandbox::Tools for HostState {
    fn dispatch(&mut self, request_json: String) -> String {
        let request: serde_json::Value = serde_json::from_str(&request_json)
            .unwrap_or(serde_json::Value::Null);
        let name = request["name"].as_str().unwrap_or("");
        let args = request.get("args").cloned().unwrap_or(serde_json::Value::Null);
        match self.tools.dispatch(name, args) {
            Ok(v) => serde_json::to_string(&serde_json::json!({"result": v}))
                .unwrap_or_else(|_| r#"{"error":"serialization failed"}"#.to_string()),
            Err(e) => serde_json::to_string(&serde_json::json!({"error": e.to_string()}))
                .unwrap_or_else(|_| r#"{"error":"serialization failed"}"#.to_string()),
        }
    }
}

// ---------------------------------------------------------------------------
// PythonSandbox
// ---------------------------------------------------------------------------

/// A ready-to-use Python execution sandbox backed by hyperlight-wasm.
pub struct PythonSandbox {
    sandbox: bindings::PythonSandboxSandbox<HostState, LoadedWasmSandbox>,
}

impl PythonSandbox {
    /// Build a new sandbox from the given configuration.
    pub fn new(config: SandboxConfig) -> Result<Self> {
        Self::with_tools(config, ToolRegistry::new())
    }

    /// Build a new sandbox with pre-registered tools.
    pub fn with_tools(config: SandboxConfig, tools: ToolRegistry) -> Result<Self> {
        let module_path = config.module_path.clone();
        let state = HostState { tools };

        let mut proto = SandboxBuilder::new()
            .with_guest_input_buffer_size(70_000_000)
            .with_guest_heap_size(config.heap_size)
            .with_guest_scratch_size(config.stack_size as usize)
            .build()
            .context("failed to build ProtoWasmSandbox")?;

        // register_host_functions binds tools.dispatch via the macro-generated code
        let rt = bindings::register_host_functions(&mut proto, state);

        let wasm_sandbox = proto
            .load_runtime()
            .context("failed to load Wasm runtime")?;

        let sb = wasm_sandbox
            .load_module(Path::new(&module_path))
            .context("failed to load Wasm module")?;

        Ok(Self {
            sandbox: bindings::PythonSandboxSandbox { sb, rt },
        })
    }

    /// Execute Python `code` in the sandbox.
    pub fn run(&mut self, code: &str) -> Result<ExecutionResult> {
        use bindings::hyperlight::sandbox::Executor;
        let wit_result = self.sandbox.run(code.to_string());

        Ok(ExecutionResult {
            stdout: wit_result.stdout,
            stderr: wit_result.stderr,
            exit_code: wit_result.exit_code,
        })
    }

    /// Take a snapshot of the current sandbox state.
    pub fn snapshot(&mut self) -> Result<Arc<Snapshot>> {
        self.sandbox
            .sb
            .snapshot()
            .map_err(|e| anyhow::anyhow!("snapshot failed: {e}"))
    }

    /// Restore the sandbox to a previously captured snapshot.
    pub fn restore(&mut self, snapshot: &Arc<Snapshot>) -> Result<()> {
        self.sandbox
            .sb
            .restore(snapshot.clone())
            .map_err(|e| anyhow::anyhow!("restore failed: {e}"))
    }
}
